### ISSUE TITLE
Ads get through twitch streams..... yet AGAIN

### ISSUE THREAD

**Issue by xNinjaRose** [odensc/ttv-ublock#16]
Ads are getting thru the extension to twitch streams AGAIN, twitch programmers are HORRIBLE, they need to quit trying to counter adblockers for pennies, all that makes them are petty. I hope u can get an update out soon

**Comment by strong-code** [comment]
Can you post more information to help identify the issue?
- your browser and version
- windows/macOS/linux?
- your installed version of this addon
- streamer you were watching
- preroll or mid-roll ad
- do you have any other conflicting addons/userscripts enabled?

**Comment by xNinjaRose** [comment]
- Chrome
- Windows 10
- Latest Version, ever since Chrome, only version since it got approved
- @ladylizzixd 
- pre-roll, i tried refreshing cuz sometimes extension takes a second to work, tho thats usually after an update/install and i was on twitch already so i had to refresh, but this time it kept giving ads
and just ublock origin, i took off the userscript a while ago(before chrome got approved) since they said it conflicted

So as u can see twitch "patched" again and this needs a new update

**Comment by DKnightX91** [comment]
I just test this, I got no ads hoping around twitch right now. I use brave, the version I use of ttv-ublock is the one you need to use dev mode (just update the code the was post here).

**Comment by strong-code** [comment]
> 
> 
>     * Chrome
> 
>     * Windows 10
> 
>     * Latest Version, ever since Chrome, only version since it got approved
> 
>     * @ladylizzixd
> 
>     * pre-roll, i tried refreshing cuz sometimes extension takes a second to work, tho thats usually after an update/install and i was on twitch already so i had to refresh, but this time it kept giving ads
>       and just ublock origin, i took off the userscript a while ago(before chrome got approved) since they said it conflicted
> 
> 
> So as u can see twitch "patched" again and this needs a new update

Thanks for the additional info. I installed the `2.0.0` version on my Chrome and didn't receive any ads. Jumped around to multiple streamers but they were all blocked successfully.

I would recommend you uninstall/reinstall the addon and additionally disable uBlock Origin on twitch, as it is not needed in conjunction with this addon. If you are still getting ads after doing that, then I would say it seems Twitch is rolling out some gradual deployment that breaks this addon.

**Comment by justinbhopper** [comment]
For what its worth, I just tried using incognito and it worked for me.

Some notes for others to ensure you are testing properly:
- Go to chrome://extensions
- Verify that the TTV ad-block extension is installed and at version 2.0.0
- Click on Details of the extension
- Ensure the "Allow in incognito" toggle is enabled
- Open someone's Twitch in an incognito window and test if ads show up immediately (aka pre-roll)
- Ads usually do not pre-roll more than once per session, which is why incognito is important

At the moment, I can perform these steps which seems clear to me that the extension is still working:
- Enable the extension, launch twitch in new incognito window: No ads
- Disable the extension, launch twitch in new incognito window: Ads pre-roll
- Re-Enable the extension, launch twitch in new incognito window: No ads

**Comment by luffydev** [comment]
I've tested the latest version of TTV ad-block and i'm not getting ads, maybe you've a problem with your addon's version or configuration ?

**Comment by Morten79** [comment]
Just tested this morning both normal logged-in and incognito mode not logged-in no pre-roll. 
I'm very grateful 👍  Thanks alot for all your hard work odensc.

**Comment by StephanBruh** [comment]
Works for me still, with the latest extensions

**Comment by odensc** [comment]
Closing this because the extension is still working AFAIK. If it's not for you, please follow @justinbhopper's steps to test it in incognito. This eliminates any other variables.
