### ISSUE TITLE
Firefox extension no longer blocking prerolls

### ISSUE THREAD

**Issue by digitaldiatribe** [odensc/ttv-ublock#20]
Hi, the addon hasn't been blocking the preroll ads for me recently. I'm not sure what changed. I went through the listed troubleshooting steps and some of my own including deleting cookies and site data for Twitch to no avail. Even went so far as to check if it's the same situation in incognito mode, which it is.

Any ideas what else I can do?

**Comment by Rookie543** [comment]
I'm facing the same issue here (firefox 83.0 x64, win10). I got prerolls since the begining of the extension.
Tried a lot of things : Firefox (cookies and cache cleared) + TTV ad-block + Ublock Origin (cache cleared, all filters checked and up to date)

New profile Firefox + only TTV ad-block, then Firefox + TTV ad-block + Ublock Origin.
Firefox portable version + only TTV ad-block then Firefox portable version  + TTV ad-block + Ublock Origin.

Uninstallation of Firefox with Revo then fresh install + all previous steps etc...

Whatever I tried, nothing has changed, I got prerolls half of time for any stream I'm starting to watch

But all along the stream it's absolutly perfect, no ads, excepted when streamer end his stream and start to host someone esle.
I got pre-rolls while the transition.

No issues on chrome.

Thank you for this great extension though.

**Comment by sixfold-origami** [comment]
I'm also getting a similar issue on firefox (no issue on chrome). Getting this screen when the page loads (it goes away after 20 seconds or so):
![tmp](https://user-images.githubusercontent.com/8202612/102672064-7e2f8080-4155-11eb-91e6-ad145553dacf.png)
I also get it periodically for (what I assume are supposed to be) midrolls.

Firefox version 83.0
Extension version 2.1.0

**Comment by BlacRyu** [comment]
> I'm also getting a similar issue on firefox (no issue on chrome). Getting this screen when the page loads (it goes away after 20 seconds or so):
> \<img\>
> 
> Firefox version 83.0
> Extension version 2.1.0

I'm getting this same screen on Chrome, using v2.1.0
![Twitch ad blocker blocker](https://user-images.githubusercontent.com/10762433/102672924-12461b80-4147-11eb-9b20-24d3ed17a6d4.png)

**Comment by odensc** [comment]
I'm not getting this yet. Can you test in incognito (without extension) on a site like twitchls.com and see if it still pops up? Trying to see if it shows up on all embeds or just detects the extension.

**Comment by polymorphicshade** [comment]
I can confirm as of about 15 min ago, my Firefox started showing that stupid purple screen.
On a Private Tab, I do not see that screen when using twitchls.com.

**Comment by sixfold-origami** [comment]
Also tested on chrome. No dumb purple screen on twitchls.com when in incognito.

**Comment by digitaldiatribe** [comment]
I'm away from my computer currently exhibiting the issue, but as of last night I was not getting the purple screen. Just a straight preroll ad.

**Comment by Rookie543** [comment]
Same here (incognito (without extension) on twitchls.com)
![firefox_ZYlMEpOi08](https://user-images.githubusercontent.com/76062785/102675428-9de89800-4199-11eb-951f-f2ec627b1376.jpg)

**Comment by sixfold-origami** [comment]
Same here, I also got a midroll on twitchtls after a bit. Apologies for my premature evaluation earlier.

**Comment by odensc** [comment]
Yeah so if they went with the nuclear option of just dropping that on any embedded player, it's not going to be as easy as I thought. Thanks everyone for checking!

**Comment by Rookie543** [comment]
Thank you odensc, you gave us one ad-free month and that was really great. I wish you good luck to find an other trick.

**Comment by PureFallen** [comment]
As usual for Twitch it is to expect that the update to the bypass is not rolled out for all people at the same time.
Different countries, different Twitch Websites. The Settingspage "Personal Ad Preferences" is not available in the US either since they don't have to ask for consent there according to the law.

To get back to the purple screen, as already noticed, the message changed to adress awareness about User Scripts as well of "if you are not already on the website". It could really be they went with the nuke option now and get all embed user involved into that.
Odensc bought us a lot of time here and we can really appreciate it. But it is time to excavate the blueprints again. The War between Twitch and Adblockers goes into the next round and Twitch apparently has awareness about this Addon and Userscripts with similar functionality again.

Edit: Figured that the purple screen not only appears on the Main Player but also the Miniplayer above the chat, so grabbing the Miniplayer for the meantime is no longer a solution either, when simulating an Embed. It could still work for trying to access the original stream.

![hIgPmN0iVy](https://user-images.githubusercontent.com/68307987/102676978-fd45a880-4197-11eb-9e26-096fe627e7c4.png)

**Comment by xzyxzy** [comment]
Saltybet is damn unwatchable now because of this shit.

**Comment by tsieczko** [comment]
![2020-12-18](https://user-images.githubusercontent.com/14418118/102679700-775d3980-4166-11eb-83fd-162552407d8a.png)

Im pretty sure twitch devs are on a warpath searching for every ad blocking method and thwarting it. At least this purple screen is better than having to watch mcdonalds travis burger ads. Thank you for you efforts odensc!

**Comment by Alvatore** [comment]
Just now got this same purple screen as a mid-roll on twitchls in a Firefox Private Browsing window, with the add-on disabled. I refreshed the stream I was watching after the mid-roll cleared, and got it again as a pre-roll.

**Comment by Tkain** [comment]
I'm encountering this too. Not sure if this helps with a temporary solution, but I've noticed that the mini-player returns to the stream quicker than the main player does by about 5 seconds. If you can draw from that feed, you might be able to make the midrolls a little less annoying. Probably requires more research though.

**Comment by odensc** [comment]
Merging into #21
